/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as CivicRouteImport } from './routes/civic'
import { Route as NightRouteImport } from './routes/night'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as CivicIndexRouteImport } from './routes/civic.index'
import { Route as CivicSlugRouteImport } from './routes/civic.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicRoute = CivicRouteImport.update({
  id: '/civic',
  path: '/civic',
  getParentRoute: () => rootRouteImport,
} as any)
const NightRoute = NightRouteImport.update({
  id: '/night',
  path: '/night',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const CivicIndexRoute = CivicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CivicRoute,
} as any)
const CivicSlugRoute = CivicSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CivicRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/civic': typeof CivicRouteWithChildren
  '/night': typeof NightRoute
  '/videos': typeof VideosRoute
  '/civic/$slug': typeof CivicSlugRoute
  '/civic/': typeof CivicIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/night': typeof NightRoute
  '/videos': typeof VideosRoute
  '/civic/$slug': typeof CivicSlugRoute
  '/civic': typeof CivicIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/archive': typeof ArchiveRoute
  '/civic': typeof CivicRouteWithChildren
  '/night': typeof NightRoute
  '/videos': typeof VideosRoute
  '/civic/$slug': typeof CivicSlugRoute
  '/civic/': typeof CivicIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/archive'
    | '/civic'
    | '/night'
    | '/videos'
    | '/civic/$slug'
    | '/civic/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/archive'
    | '/night'
    | '/videos'
    | '/civic/$slug'
    | '/civic'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/archive'
    | '/civic'
    | '/night'
    | '/videos'
    | '/civic/$slug'
    | '/civic/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ArchiveRoute: typeof ArchiveRoute
  CivicRoute: typeof CivicRouteWithChildren
  NightRoute: typeof NightRoute
  VideosRoute: typeof VideosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic': {
      id: '/civic'
      path: '/civic'
      fullPath: '/civic'
      preLoaderRoute: typeof CivicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/night': {
      id: '/night'
      path: '/night'
      fullPath: '/night'
      preLoaderRoute: typeof NightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/civic/': {
      id: '/civic/'
      path: '/'
      fullPath: '/civic/'
      preLoaderRoute: typeof CivicIndexRouteImport
      parentRoute: typeof CivicRoute
    }
    '/civic/$slug': {
      id: '/civic/$slug'
      path: '/$slug'
      fullPath: '/civic/$slug'
      preLoaderRoute: typeof CivicSlugRouteImport
      parentRoute: typeof CivicRoute
    }
  }
}

interface CivicRouteChildren {
  CivicSlugRoute: typeof CivicSlugRoute
  CivicIndexRoute: typeof CivicIndexRoute
}

const CivicRouteChildren: CivicRouteChildren = {
  CivicSlugRoute: CivicSlugRoute,
  CivicIndexRoute: CivicIndexRoute,
}

const CivicRouteWithChildren = CivicRoute._addFileChildren(CivicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ArchiveRoute: ArchiveRoute,
  CivicRoute: CivicRouteWithChildren,
  NightRoute: NightRoute,
  VideosRoute: VideosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
